global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
        - '172.168.10.131:9100'
        - '172.168.10.137:9100'
        - '172.168.10.138:9100'

  - job_name: 'dcgm_exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
        - '172.168.10.131:9400'
        - '172.168.10.137:9400'
        - '172.168.10.138:9400'

  - job_name: 'nvidia_smi_exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
          - '172.168.10.131:9835'
          - '172.168.10.137:9835'
          - '172.168.10.138:9835'

  - job_name: 'mtail'
    scrape_interval: 2s
    static_configs:
      - targets: ['172.168.15.34:3903']

  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - '172.168.15.34:8080'
        - '172.168.10.131:8080'